### ISSUE TITLE
Where are the Hebrew samples published at w3c/typography ?

### ISSUE THREAD

**Issue by tomerm** [w3c/hlreq#5]
@r12a Apologizes in advance. Hopefully you can help me understand the situation / process better. I published several examples of Hebrew script presentation on w3c/typography. They are completely gone. Some of them were moved to w3c/hlreq. But not all of them. For example there was an issue on hyphenation and also on Hebrew letters which are stretched to fit line. By the way Arabic examples are gone as well from w3c/typography. Can you please shed some light on that (I just don't want to spin my wheels in vain here). 

I asked some of my colleagues to publish their cases on w3c/typography as well. I would like to avoid situation in which they suddenly discover that their work was simply removed. 

Apologies for any misunderstanding in advance.

**Comment by r12a** [comment]
hi @tomerm, they should all still be there.  As you know, this repo and concept is very new, and i've been trying to figure out what's the best way to organize the repo and annotate the samples.  The aim is for this to be a highly structured repo organized around individual images, that allows people to easily find and use those images.

After initial thought, discussion and some programming, i came up with a format and approach which i hope will work, and which is documented at https://github.com/w3c/type-samples under "How to submit an image".  Over the weekend i converted all the issues we have so far to conform to that format.

The easiest way to find the current location of your Hebrew samples is to use the index at https://w3c.github.io/type-samples/.  Click on 'Hebrew' in the right-hand column, then to access a particular image click on the image thumbnail.

The images (but not the metadata) are also available in the github directory structure. For example, https://github.com/w3c/type-samples/tree/gh-pages/hebr/he. The main advantage of this is that you can easily obtain local copies of all the images by cloning the repository.

If you want to use an image, you can take copies of the image for use in other documents (drag and drop to a local directory is a simple way to get a copy).  In some circumstances, you may instead simply link to either an issue (like i did at https://github.com/w3c/mlreq/issues/5 this morning), or link to just the image using the filename, such as https://w3c.github.io/type-samples/hebr/he/2bc7a9c6-f88e-11e6-97f7-47f05b7fd7ec.png.

The issues i moved to hlreq were just those that described how Hebrew features work (because i thought they were quite useful(!) as potential initial drafts for the hlreq document).

Does that make things clearer?  If your colleagues want to submit  images, please ask them to follow the guidelines at https://w3c.github.io/type-samples/, and ping me if anything is unclear.

**Comment by tomerm** [comment]
@r12a thanks a lot ! Not sure what happened and for what reason I stopped seeing the issues. I do see them now with simplest filtering (i.e. label = hebrew): https://github.com/w3c/type-samples/issues?q=is%3Aopen+is%3Aissue+label%3Ahebrew

Thanks again for the very detailed reply. Appreciate it. 
I will instruct my colleagues to use https://w3c.github.io/type-samples/ as a guidance.
